branches:
  only:
    - master
language: python
matrix:
  include:
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true
install:
  - pip install -r requirements-dev.txt
script:
  - make test